export const dummyData = [
  {
    id: 0,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 1,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 2,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 3,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 4,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 5,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 6,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 7,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 8,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 9,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 10,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 11,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 12,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 13,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 14,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 15,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 16,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 17,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
  {
    id: 18,
    vote: 1,
    answer: 2,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
  },
];
