import { dummyAnswerData } from './dummyAnswerData';
export const dummyData = [
  {
    // question 고유 아이디
    id: 0,
    // question 추천 수
    vote: 1,
    // question 조회수
    views: 18,
    // question 제목
    title: 'how redirect user with stripe react component and django',
    // question_List에 보이는 제목
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    // question 태그's
    tags: ['python', 'reactjs', 'django', 'abcdefg'],
    // question 작성자 정보
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    // question 작성 시간
    time: new Date(),
    // question detail 내용
    content: [
      `I would like to redirect my user after he has made a payment (successful or failed) to a page automatically.`,
      `Currently, the payment is going well, the update is a success on stripe and I manage to retrieve the necessary information with my django view.`,
      `However, after successful payment, no redirection takes place. There are several documentation but I cant find a way to do it with the react component proposed by stripe themselves.`,
      `How can I proceed?`,
      `here is my work`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
    ],
    // 답변 관련 정보
    answer: dummyAnswerData,
  },
  {
    id: 1,
    vote: 1,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
    content: [
      `I would like to redirect my user after he has made a payment (successful or failed) to a page automatically.`,
      `Currently, the payment is going well, the update is a success on stripe and I manage to retrieve the necessary information with my django view.`,
      `However, after successful payment, no redirection takes place. There are several documentation but I cant find a way to do it with the react component proposed by stripe themselves.`,
      `How can I proceed?`,
      `here is my work`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
    ],
    answer: dummyAnswerData,
  },
  {
    id: 2,
    vote: 1,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
    content: [
      `I would like to redirect my user after he has made a payment (successful or failed) to a page automatically.`,
      `Currently, the payment is going well, the update is a success on stripe and I manage to retrieve the necessary information with my django view.`,
      `However, after successful payment, no redirection takes place. There are several documentation but I cant find a way to do it with the react component proposed by stripe themselves.`,
      `How can I proceed?`,
      `here is my work`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
    ],
    answer: dummyAnswerData,
  },
  {
    id: 3,
    vote: 1,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
    content: [
      `I would like to redirect my user after he has made a payment (successful or failed) to a page automatically.`,
      `Currently, the payment is going well, the update is a success on stripe and I manage to retrieve the necessary information with my django view.`,
      `However, after successful payment, no redirection takes place. There are several documentation but I cant find a way to do it with the react component proposed by stripe themselves.`,
      `How can I proceed?`,
      `here is my work`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
    ],
    answer: dummyAnswerData,
  },
  {
    id: 4,
    vote: 1,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
    content: [
      `I would like to redirect my user after he has made a payment (successful or failed) to a page automatically.`,
      `Currently, the payment is going well, the update is a success on stripe and I manage to retrieve the necessary information with my django view.`,
      `However, after successful payment, no redirection takes place. There are several documentation but I cant find a way to do it with the react component proposed by stripe themselves.`,
      `How can I proceed?`,
      `here is my work`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
    ],
    answer: dummyAnswerData,
  },
  {
    id: 5,
    vote: 1,
    views: 18,
    title: 'how redirect user with stripe react component and django',
    body: 'I would like to redirect my user after he has made a payment (successful or failed) to a page automatically. Currently, the payment is going well, the update is a success on stripe and I manage to ...',
    tags: ['python', 'reactjs', 'django'],
    author: {
      name: 'yuting',
      answered: 635,
      avatar: 'Img',
    },
    time: new Date(),
    content: [
      `I would like to redirect my user after he has made a payment (successful or failed) to a page automatically.`,
      `Currently, the payment is going well, the update is a success on stripe and I manage to retrieve the necessary information with my django view.`,
      `However, after successful payment, no redirection takes place. There are several documentation but I cant find a way to do it with the react component proposed by stripe themselves.`,
      `How can I proceed?`,
      `here is my work`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
      `Offers.js : ReactComponent by Stripe`,
      `    <stripe-pricing-table`,
      `      pricing-table-id="prctbl_<my_pricing_table_key>"`,
      `      publishable-key="pk_test_<my-stripe-public-key>"`,
      `      // user informations for update subscriptions django model`,
      `      customer-email={asdf}`,
      `      client-reference-id={asdf}`,
      `    >`,
      `    </stripe-pricing-table>`,
    ],
    answer: dummyAnswerData,
  },
];
