server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://database-1.c16y5acx5nnq.ap-northeast-2.rds.amazonaws.com:3306/preproject28?serverTimezone=Asia/Seoul
    username: admin
    password: GQyMD4Ih5VnC3m6ALwOK
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
mail:
  address:
    admin: admin@gmail.com
jwt:
#  key: ${JWT_SECRET_KEY}               # 민감한 정보는 시스템 환경 변수에서 로드한다.
  key: minho1234123412341234123412341234               # 민감한 정보는 시스템 환경 변수에서 로드한다.
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420