server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/preproject28?serverTimezone=Asia/Seoul
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true